### ISSUE TITLE
Mapple runnning on Model JC throws an error 

### ISSUE THREAD

**Issue by josenikhid97** [NicolaDM/MAPLE#10]
Hi @team_MAPLE

Today i tried to run the mapple with model JC and shows me an error on the line 4401 mentioned about the "name  pseudoMUTcounts is not defined" . but the same data sets work fine with other models like UNREST and GTR.
![maple_jc eroor](https://user-images.githubusercontent.com/64956458/173041730-0baa68f6-af60-4d2c-bb16-68a6c549ad3d.png)

waiting to hear from you back as soon as possible

**Comment by NicolaDM** [comment]
Thanks for letting me know! I have now fixed this as of version v0.1.0

**Comment by josenikhid97** [comment]
Hi

Thank you for your Quick reply and the JC model works fine :)
