### ISSUE TITLE
what the diff with usher?

### ISSUE THREAD

**Issue by liamxg** [NicolaDM/MAPLE#13]

**Comment by NicolaDM** [comment]
There are similarities between MAPLE and UShER followed by matOptimize.
The main difference is that UShER and matOptimize are parsimony-based methods, while MAPLE is a maximum likelihood approach (although with some parsimony-like features). Some consequence of this is that UShER and matOptimize have the potential of being more memory and time efficient, while MAPLE can include more refined evolutionary models and data and so in principle have more applications and higher accuracy.
You can find in the manuscript a comparison of the two methods in terms of performance, although I would argue the main advantage of MAPLE is really the flexibility given by a likelihood-based approach, which I hope will become clear as more work is put in extending and applying it.

**Comment by liamxg** [comment]
thanks, this is very helpful to me. will this be a new software or something?

**Comment by liamxg** [comment]
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/46078579/180382658-954410df-c6d2-4d4b-92d4-1d57e515329b.png">

**Comment by liamxg** [comment]
this is run with maple, is this normal?

**Comment by NicolaDM** [comment]
MAPLE is already a new software, completely separate from UShER, matUtils, etc.
However, it will be nice in the future to allow the same methodology within UShER, as well as within other phylogenetic packages.

Regarding your example, what is strange about it? If you mean the branch lengths in comparison to UShER's branch lengths, the thing is that branch lengths in MAPLE are comparable to those in other maximum likelihood methods, like fasttree, IQ-TREE, RAxML, etc. A length of 0.001 means 0.001 expected mutations per site on that branch. To get a rough translation of these branch lengths into number of mutations per branch you can simply multiply them by the genome length.

**Comment by liamxg** [comment]
thanks, that's really helpful.
