### ISSUE TITLE
what is the diff betwee maple and fastree?

### ISSUE THREAD

**Issue by liamxg** [NicolaDM/MAPLE#14]

**Comment by NicolaDM** [comment]
MAPLE is a maximum likelihood method just like FastTree2, IQ-TREE2 and RAxML; however, MAPLE is tailored for datasets where branch lengths are short, such as in genomic epidemiology.
MAPLE implements new algorithms and approximations to make inference in this scenario less memory intensive, faster, and more accurate.
See manuscript for a full comparison of these methods and a description of the MAPLE approach:
https://doi.org/10.1101/2022.03.22.485312

**Comment by liamxg** [comment]
thanks.
