### ISSUE TITLE
More compact diff file?

### ISSUE THREAD

**Issue by tseemann** [NicolaDM/MAPLE#5]
I ran `creafeDiff` on an alignment of 25,000 COVID seqiuences.
The diff file was 13 million lines.
Most of the lines are for `N` bases.

```
grep -v '^>' maple.diff  | cut -f1 | sort | uniq -c | sort -nr
11507656 N
 601538 T
 386471 A
 291184 G
 191800 C
```

Most of these occur in runs of `NNNNNNNN` at the 3' and 5' ends, or in regions of amplicon dropouts.

Perhaps these could be 'run length encoded:
````
1-287     N
12945-12458.   N
```
Or perhaps accept .gz encoded files?

**Comment by corneliusroemer** [comment]
The example diff file has some sort of run length encoding if I'm not mistaken.

Maybe the `create_diff` script doesn't use this option though.

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/25161793/160719331-2805330e-3dec-499a-8798-6f03413ee6de.png">

**Comment by NicolaDM** [comment]
Sorry about that, the script was thrown off by input uppercase sequences! I have now fixed the bug.
