### ISSUE TITLE
Still running after 7 hours

### ISSUE THREAD

**Issue by tseemann** [NicolaDM/MAPLE#6]
```Processed topology for 24500 nodes.
Processed topology for 25000 nodes.
Processed topology for 25500 nodes.
Processed topology for 26000 nodes.
Processed topology for 26500 nodes.
Processed topology for 27000 nodes.
Processed topology for 27500 nodes.
Processed topology for 28000 nodes.```

It has been going for 7 hours and still going for N=25780 alignment.

Is this expected?

**Comment by NicolaDM** [comment]
Yes, these rounds of topological improvements can be demanding.
You can reduce the runtime by reducing the number of topology improvement rounds using the --numTopologyImprovements option, setting it to 0 will only perform the initial tree building (which is not bad in itself); if you increase it, for example to 1, it will also perform one round of topological improvements. By default it's 3, which is quite thorough.

If you use pypy the software runs faster, but I think you are already using it, right?

**Comment by NicolaDM** [comment]
I have now rewritten the code to improve its efficiency. From MAPLE v0.0.5 onward analyses should now run several times faster and use less memory while also being more accurate.
I will update the manuscript soon accordingly.
For 25,000 SARS-CoV-2 genomes MAPLE should now take little more than 1 hour when run with pypy3.
I also added option --fast for additional speed; this might however compromise some accuracy on complex datasets with recombination, sequencing errors, etc!
